services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../c4b:/c4b:cached,rw
      - ..:/ROOT:cached,rw

    command: sleep infinity

    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
